"""empty message

Revision ID: f20dc53fb715
Revises: 444edbb0bc36
Create Date: 2023-08-15 14:40:59.322752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20dc53fb715'
down_revision = '444edbb0bc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('personaje_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'personajes', ['personaje_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'planetas', ['planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('personaje_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
